Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-06, with the labels that each got.

#114 chore: Storybook 셋팅
  .eslintrc.json
  .github/workflows/storybook.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/stories/common/Button.stories.tsx
  src/stories/story.styles.ts
Labels: ⚙️chore, ✔︎pull requests, 👩🏻‍💻 frontend

#116 feat: 디자인 시스템 세팅
  src/assets/fonts/PretendardVariable.woff2
  src/components/Buttons/SortButton.tsx
  src/components/Buttons/TagButton.tsx
  src/components/Buttons/ToggleButton.tsx
  src/components/CreatPostPage/CreatePostForm.tsx
  src/components/CreatPostPage/ImageDropZone.tsx
  src/components/LandingPage/MainPost.style.ts
  src/components/LandingPage/MainPost.tsx
  src/components/LandingPage/VoteButton.tsx
  src/components/PostListPage/CreatePostButton.tsx
  src/components/PostListPage/PostItem.style.ts
  src/components/PostListPage/PostItem.tsx
  src/components/PostListPage/PostItemImage.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/PostImage/PostImage.sylte.ts
  src/components/common/UserComment/UserComment.style.ts
  src/components/common/UserProfile.tsx
  src/layout/Header/Header.style.ts
  src/layout/Header/Login/Login.tsx
  src/layout/Header/Logout/Logout.tsx
  src/pages/CreatePostPage/CreatePostPage.style.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/PostListPage/PostListPage.tsx
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.style.ts
  src/pages/PostPage/CreatorSection/CreatorSection.style.ts
  src/pages/PostPage/TitleSection/TitleSection.style.ts
  src/pages/SearchResultPage/SearchResultPage.tsx
  src/styles/color.ts
  src/styles/index.css
  src/styles/reset.css
  src/styles/typo.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#120 design: Chips 및 상단 배너 컴포넌트 UI 구현
  src/components/common/Chips/Chips.style.ts
  src/components/common/Chips/Chips.tsx
  src/components/pattern/TopBanner/TopBanner.style.ts
  src/components/pattern/TopBanner/TopBanner.tsx
  src/stories/common/Button.stories.tsx
  src/stories/common/Chips.stories.tsx
  src/stories/pattern/TopBanner.stories.tsx
  src/styles/keyframes.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend

#123 design: Button, Input, Heading 컴포넌트 구현 및 스토리 작성
  src/assets/svg/Email.svg
  src/components/common/Button/Button.style.ts
  src/components/common/Button/Button.tsx
  src/components/common/ErrorMessage/ErrorMessage.style.ts
  src/components/common/ErrorMessage/ErrorMessage.tsx
  src/components/common/Heading/Heading.style.ts
  src/components/common/Heading/Heading.tsx
  src/components/common/Input/Input.style.ts
  src/components/common/Input/Input.tsx
  src/components/common/InputComment/InputEditedComment/InputEditedComment.tsx
  src/components/common/InputComment/InputNewComment/InputNewComment.tsx
  src/components/common/InputComment/InputNewReply/InputNewReply.tsx
  src/components/common/InputsUserInfo/InputCode.tsx
  src/components/common/InputsUserInfo/InputEmail.tsx
  src/components/common/InputsUserInfo/InputNickname.tsx
  src/components/common/InputsUserInfo/InputProfileImage/InputProfileImage.tsx
  src/components/common/InputsUserInfo/InputPw.tsx
  src/components/common/InputsUserInfo/InputPwCheck.tsx
  src/components/common/Label/Label.style.ts
  src/components/common/Label/Label.tsx
  src/components/common/Modal/ChangeVoteModal/ChangeVoteModal.tsx
  src/components/common/Modal/DeleteCommentModal/DeleteCommentModal.tsx
  src/components/common/Modal/LoginModal/LoginModal.tsx
  src/components/common/Modal/ProfileModal/ProfileModal.tsx
  src/components/common/Modal/ReportModal/ReportModal.tsx
  src/components/design/Button/Button.style.ts
  src/components/design/ErrorMessage/ErrorMessage.style.ts
  src/components/design/Heading/Heading.style.ts
  src/components/design/Heading/Heading.tsx
  src/components/design/Input/Input.style.ts
  src/components/design/Label/Label.style.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/FindPasswordPage/FindPasswordPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/sections/LoginForm/LoginForm.tsx
  src/pages/MyPage/DeletePage/DeletePage.tsx
  src/pages/MyPage/DeletePage/sections/DeleteForm/DeleteForm.tsx
  src/pages/MyPage/HistoryPage/TabPage/BookmarksPage/BookmarksPage.tsx
  src/pages/MyPage/UpdatePage/UpdatePage.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/PostListPage/PostListPage.tsx
  src/pages/SearchResultPage/SearchResultPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/stories/common/Button.stories.tsx
  src/stories/common/ErrorMessage.stories.tsx
  src/stories/common/Heading.stories.tsx
  src/stories/common/Input.stories.tsx
  src/stories/common/Label.stories.tsx
  src/stories/story.styles.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup

#124 design: ChallengeButton, Profile, GameCard 컴포넌트 구현 및 스토리 작성
  src/assets/index.ts
  src/assets/svg/normal-profile.svg
  src/assets/svg/right-arrow.svg
  src/components/common/ChallengeButton/ChallengeButton.style.ts
  src/components/common/ChallengeButton/ChallengeButton.tsx
  src/components/common/ProfileIcon/ProfileIcon.style.ts
  src/components/common/ProfileIcon/ProfileIcon.tsx
  src/components/pattern/GameCard/GameCard.style.ts
  src/components/pattern/GameCard/GameCard.tsx
  src/stories/common/ChallengeButton.stories.tsx
  src/stories/common/ProfileIcon.stories.tsx
  src/stories/pattern/GameCard.stories.tsx
  src/stories/story.styles.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup
