Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-02, with the labels that each got.

#20 feat: carousel 기능 구현
  src/assets/svg/LeftArrowButton.tsx
  src/assets/svg/RightArrowButton.tsx
  src/components/Carousel.tsx
  src/components/Pagination.tsx
  src/pages/LandingPage/LandingPage.tsx
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#21 게시글 본문 페이지 UI 마크업 및 공통 컴포넌트(Header, SearchBar, Footer) 구현 완료
  src/App.tsx
  src/assets/svg/LikeIcon.tsx
  src/assets/svg/MoreIcon.tsx
  src/assets/svg/ReportIcon.tsx
  src/assets/svg/SearchIcon.tsx
  src/assets/svg/ShareIcon.tsx
  src/assets/svg/StarIcon.tsx
  src/components/CommentSection.tsx
  src/components/IconList.tsx
  src/components/PostOptionCard.tsx
  src/components/UserComment.tsx
  src/components/UserProfile.tsx
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/SearchBar.tsx
  src/pages/PostPage/PostPage.tsx
  src/styles/reset.css
Labels: 🎨 markup

#23 msw 환경 설정
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/Carousel.tsx
  src/components/Pagination.tsx
  src/index.tsx
  src/mocks/browser.ts
  src/mocks/data/posts.ts
  src/mocks/handlers.ts
  src/pages/LandingPage/LandingPage.tsx
Labels: ⚙️chore, ✔︎pull requests, 👩🏻‍💻 frontend

#24 feat: 로그인, 회원가입, 비밀번호 찾기 ui 마크업 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svg/Email.tsx
  src/assets/svg/Key.tsx
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/components/ErrorMessage/ErrorMessage.style.ts
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/Heading/Heading.style.ts
  src/components/Heading/Heading.tsx
  src/components/ImageDropZone.tsx
  src/components/Input/Input.style.ts
  src/components/Input/Input.tsx
  src/components/Label/Label.style.ts
  src/components/Label/Label.tsx
  src/components/MainPost.tsx
  src/components/PostImage.tsx
  src/components/SortButton.tsx
  src/components/TagButton.tsx
  src/components/ToggleButton.tsx
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/CreatePostPage/sections/CreatePostForm.tsx
  src/pages/FindPasswordPage/FindPasswordPage.style.ts
  src/pages/FindPasswordPage/FindPasswordPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/PostListPage/PostListPage.tsx
  src/pages/PostListPage/sections/PostItem.tsx
  src/pages/PostListPage/sections/PostItemImage.tsx
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/styles/Theme.ts
  src/styles/reset.css
  src/types/temp.ts
  tsconfig.json
  webpack.config.js
Labels: ⚙️chore, ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup, 🙆‍♀️회원가입, 🗝️로그인

#26 feat: 로그인, 비밀번호 찾기, 회원가입 ui 마크업 보충 구현
  .eslintrc.json
  package-lock.json
  src/App.tsx
  src/assets/images/defaultProfile.png
  src/components/Button/Button.style.ts
  src/components/Button/Button.tsx
  src/components/Carousel.tsx
  src/components/CommentSection.tsx
  src/components/IconList.tsx
  src/components/Input/Input.style.ts
  src/components/Input/Input.tsx
  src/components/InputsUserInfo/InputCode.tsx
  src/components/InputsUserInfo/InputEmail.tsx
  src/components/InputsUserInfo/InputNickname.tsx
  src/components/InputsUserInfo/InputProfileImage/InputProfileImage.style.ts
  src/components/InputsUserInfo/InputProfileImage/InputProfileImage.tsx
  src/components/InputsUserInfo/InputPw.tsx
  src/components/InputsUserInfo/InputPwCheck.tsx
  src/components/Pagination.tsx
  src/components/PostOptionCard.tsx
  src/components/Profile/Profile.tsx
  src/components/Profile/ProfileImage/ProfileImage.style.ts
  src/components/Profile/ProfileImage/ProfileImage.tsx
  src/components/UserComment.tsx
  src/components/UserProfile.tsx
  src/constants/message.ts
  src/constants/path.ts
  src/layout/Footer.tsx
  src/layout/Header.tsx
  src/layout/SearchBar.tsx
  src/layout/layout.tsx
  src/pages/FindPasswordPage/FindPasswordPage.style.ts
  src/pages/FindPasswordPage/FindPasswordPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
Labels: ⚙️chore, 👩🏻‍💻 frontend, 🎨 markup, 🙆‍♀️회원가입, 🗝️로그인

#28 MSW를 통해 가져온 데이터를 사용해 UI 그리기
  package-lock.json
  package.json
  src/App.tsx
  src/components/ImageDropZone.tsx
  src/components/MainPost.tsx
  src/components/PostImage.tsx
  src/hooks/useInputs.ts
  src/mocks/browser.ts
  src/mocks/data/posts.ts
  src/mocks/handlers.ts
  src/mocks/handlers/handlers.ts
  src/mocks/handlers/post.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/CreatePostPage/sections/CreatePostForm.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/PostListPage/PostListPage.tsx
  src/pages/PostListPage/sections/PostItem.tsx
  src/pages/PostListPage/sections/PostItemImage.tsx
  src/pages/PostPage/PostPage.tsx
  src/providers/ReactQueryProvider.tsx
  src/types/post.ts
  src/types/temp.ts
Labels: ⚙️chore, ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend

#31 svg 사용을 위한 환경설정 및 게시물 페이지 리팩토링 완료
  package-lock.json
  package.json
  src/assets/index.ts
  src/assets/svg/like.svg
  src/assets/svg/more.svg
  src/assets/svg/plus.svg
  src/assets/svg/profile.svg
  src/assets/svg/report.svg
  src/assets/svg/share.svg
  src/assets/svg/star.svg
  src/components/IconList.tsx
  src/components/PostOptionCard.tsx
  src/components/UserComment.tsx
  src/components/UserProfile.tsx
  src/pages/PostPage/CommentsSection/CommentsByOption/CommentsByOption.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/PostCardsSection/PostCardsSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/types/custom.d.ts
  webpack.config.js
Labels: 🪄refactor, 🛠 setting, 🪧 게시물

#35 Feat: 랜딩, 게시글 목록 페이지에서 좋아요 기능 구현
  src/api/posts/posts.ts
  src/assets/index.ts
  src/assets/svg/Heart.tsx
  src/assets/svg/Hearts.svg
  src/components/HeartButton.tsx
  src/components/MainPost.tsx
  src/layout/Header.tsx
  src/mocks/data/posts.ts
  src/mocks/handlers/post.ts
  src/pages/LandingPage/LandingPage.tsx
  src/pages/PostListPage/PostListPage.tsx
  src/pages/PostListPage/sections/PostItem.tsx
  src/pages/PostPage/PostCardsSection/PostCardsSection.tsx
  tsconfig.json
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup, ✅feature

#37 mediaQuery breakpoint 설정
  src/styles/Theme.ts
Labels: ⚙️chore, 👩🏻‍💻 frontend, 🎨 markup

#41 chore: axios 설정
  package-lock.json
  package.json
  src/api/interceptor.ts
  src/constants/api.ts
  src/pages/MyPage/DeletePage/DeletePage.tsx
  src/types/mypage.ts
  tsconfig.json
Labels: ⚙️chore, ✔︎pull requests, 👩🏻‍💻 frontend

#43 MSW를 사용하여 게시물 정보, 멤버 정보를 가져오는 기능 구현
  src/api/member/member.ts
  src/api/posts/posts.ts
  src/components/BalacneOptionCard.tsx
  src/components/UserComment.tsx
  src/mocks/data/member.ts
  src/mocks/data/posts.ts
  src/mocks/handlers/handlers.ts
  src/mocks/handlers/member.ts
  src/mocks/handlers/post.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/CommentsSection/CommentsByOption/CommentsByOption.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/CreatorSection/CreatorSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/UserUtilitySection/UserUtilitySection.tsx
  src/types/member.ts
  src/types/post.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🪧 게시물, 🪄 Mocking
