Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-11, with the labels that each got.

#202 feat: 댓글 및 답글 기능 구현 및 톡픽 요약 api 수정
  src/api/comments.ts
  src/api/talk-pick.ts
  src/assets/index.ts
  src/assets/svg/more-reply.svg
  src/components/atoms/Button/Button.style.ts
  src/components/atoms/CategoryBarChip/CategoryBarChip.style.ts
  src/components/atoms/CategoryBarChip/CategoryBarChip.tsx
  src/components/atoms/CommentProfile/CommentProfile.style.ts
  src/components/atoms/CommentProfile/CommentProfile.tsx
  src/components/atoms/LikeButton/LikeButton.style.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/MoreButton/MoreButton.style.ts
  src/components/atoms/MoreButton/MoreButton.tsx
  src/components/molecules/CommentItem/CommentItem.style.ts
  src/components/molecules/CommentItem/CommentItem.tsx
  src/components/molecules/ReplyItem/ReplyItem.style.ts
  src/components/molecules/ReplyItem/ReplyItem.tsx
  src/components/molecules/TextArea/TextArea.style.ts
  src/components/molecules/TextArea/TextArea.tsx
  src/components/organisms/CommentsSection/CommentsSection.style.ts
  src/components/organisms/CommentsSection/CommentsSection.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
  src/constants/api.ts
  src/constants/message.ts
  src/constants/reportOption.ts
  src/hooks/api/comment/useCreateCommentMutation.ts
  src/hooks/api/comment/useCreateReplyMutation.ts
  src/hooks/api/comment/useDeleteCommentMutation.ts
  src/hooks/api/comment/useEditCommentMutation.ts
  src/hooks/api/comment/useRepliesQuery.ts
  src/hooks/api/like/useCreateLikeCommentMutation.ts
  src/hooks/api/like/useDeleteLikeCommentMutation.ts
  src/hooks/api/report/useReportCommentMutation.ts
  src/hooks/api/talk-pick/useCreateTalkPickMutation.ts
  src/hooks/api/talk-pick/useEditTalkPickMutation.ts
  src/hooks/comment/useCommentActions.ts
  src/hooks/common/useOutsideClick.ts
  src/pages/TalkPickPage/TalkPickPage.tsx
  src/stories/atoms/CategoryBarChip.stories.tsx
  src/stories/atoms/CommentProfile.stories.tsx
  src/stories/atoms/MoreButton.stories.tsx
  src/stories/molecules/CommentItem.stories.tsx
  src/stories/molecules/ReplyItem.stories.tsx
  src/stories/molecules/TextArea.stories.tsx
  src/stories/organisms/CommentsSection.stories.tsx
  src/types/comment.ts
  src/utils/formatData.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup, ✅feature

#204 feat: 로딩 중 스켈레톤 UI 구현
  src/App.tsx
  src/components/atoms/MypageCardSkeleton/MypageCardSkeleton.style.ts
  src/components/atoms/MypageCardSkeleton/MypageCardSkeleton.tsx
  src/components/atoms/MypageListSkeleton/MypageListSkeleton.style.ts
  src/components/atoms/MypageListSkeleton/MypageListSkeleton.tsx
  src/components/atoms/ProfileIcon/ProfileIcon.tsx
  src/components/atoms/SearchResultCardSkeleton/SearchResultCardSkeleton.style.ts
  src/components/atoms/SearchResultCardSkeleton/SearchResultCardSkeleton.tsx
  src/components/atoms/SearchResultListSkeleton/SearchResultListSkeleton.style.ts
  src/components/atoms/SearchResultListSkeleton/SearchResultListSkeleton.tsx
  src/components/organisms/SideBar/SideBar.style.ts
  src/components/organisms/SideBar/SideBar.tsx
  src/hooks/api/mypages/useGameBookmarksQuery.ts
  src/hooks/api/mypages/useGameVotesQuery.ts
  src/hooks/api/mypages/useGameWrittensQuery.ts
  src/hooks/api/mypages/useInfiniteScroll.ts
  src/hooks/api/mypages/useMyBookmarksQuery.ts
  src/hooks/api/mypages/useMyCommentsQuery.ts
  src/hooks/api/mypages/useMyInfoQuery.ts
  src/hooks/api/mypages/useMyVotesQuery.ts
  src/hooks/api/mypages/useMyWrittensQuery.ts
  src/layout/layout.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/stories/atoms/MypageCardSkeleton.stories.tsx
  src/stories/atoms/MypageListSkeleton.stories.tsx
  src/stories/atoms/SearchResultCardSkeleton.stories.tsx
  src/stories/atoms/SearchResultListSkeleton.stories.tsx
  src/stories/organisms/SideBar.stories.tsx
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#201 feat: 검색결과 api 연동
  src/App.tsx
  src/api/search.ts
  src/components/atoms/Pagination/Pagination.tsx
  src/components/atoms/SearchBar/SearchBar.tsx
  src/components/atoms/SearchTalkPickItem/SearchTalkPickItem.style.ts
  src/components/atoms/SearchTalkPickItem/SearchTalkPickItem.tsx
  src/components/atoms/ToggleGroup/ToggleGroup.tsx
  src/components/molecules/ContentsButton/ContentsButton.style.ts
  src/components/molecules/ContentsButton/ContentsButton.tsx
  src/components/molecules/SearchGameList/SearchGameList.style.ts
  src/components/molecules/SearchGameList/SearchGameList.tsx
  src/components/molecules/SearchResultBar/SearchResultBar.tsx
  src/components/molecules/SearchTagBar/SearchTagBar.tsx
  src/components/molecules/SearchTalkPickList/SearchTalkPickList.style.ts
  src/components/molecules/SearchTalkPickList/SearchTalkPickList.tsx
  src/components/organisms/BalanceGameList/BalanceGameList.tsx
  src/components/organisms/MyBalanceGameList/MyBalanceGameList.tsx
  src/components/organisms/SearchGameListSection/SearchGameListSection.style.ts
  src/components/organisms/SearchGameListSection/SearchGameListSection.tsx
  src/components/organisms/SearchGameResult/SearchGameResult.style.ts
  src/components/organisms/SearchGameResult/SearchGameResult.tsx
  src/components/organisms/SearchResultBarContainer/SearchResultBarContainer.tsx
  src/components/organisms/SearchTalkPickListSection/SearchTalkPickListSection.style.ts
  src/components/organisms/SearchTalkPickListSection/SearchTalkPickListSection.tsx
  src/components/organisms/SearchTalkPickResult/SearchTalkPickResult.style.ts
  src/components/organisms/SearchTalkPickResult/SearchTalkPickResult.tsx
  src/components/organisms/TalkPickListSection/TalkPickListSection.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/search/useGameResultQuery.ts
  src/hooks/api/search/useTalkPickResultQuery.ts
  src/hooks/search/usePagination.ts
  src/hooks/search/useSearchQuery.ts
  src/hooks/search/useSort.ts
  src/hooks/search/useTagFilter.ts
  src/pages/LandingPage/LandingPage.tsx
  src/pages/SearchResultsPage/SearchGamePage.tsx
  src/pages/SearchResultsPage/SearchResultsPage.style.ts
  src/pages/SearchResultsPage/SearchResultsPage.tsx
  src/pages/SearchResultsPage/SearchTalkPickPage.tsx
  src/pages/TalkPickPlacePage/TalkPickPlacePage.tsx
  src/stories/atoms/SearchBar.stories.tsx
  src/stories/atoms/SearchTalkPickItem.stories.tsx
  src/stories/atoms/ToggleGroup.stories.tsx
  src/stories/molecules/ContentsButton.stories.tsx
  src/stories/molecules/SearchGameList.stories.tsx
  src/stories/molecules/SearchResultBar.stories.tsx
  src/stories/molecules/SearchTagBar.stories.tsx
  src/stories/molecules/SearchTalkPickList.stories.tsx
  src/stories/organisms/BalanceGameList.stories.tsx
  src/stories/organisms/SearchGameListSection.stories.tsx
  src/stories/organisms/SearchGameResult.stories.tsx
  src/stories/organisms/SearchTalkPickListSection.stories.tsx
  src/stories/organisms/SearchTalkPickResult.stories.tsx
  src/stories/organisms/TalkPickListSection.stories.tsx
  src/types/search.ts
  src/utils/highlightText.ts
Labels: 👩🏻‍💻 frontend, 🪄refactor, ✅feature

#209 chore: SonarCloud 및 빌드 파이프라인 설정
  .github/workflows/ci.yml
  sonar-project.properties
Labels: ⚙️chore

#219 chore: 배포 환경에서 AxiosInterceptor 설정
  package-lock.json
  package.json
  public/index.html
  src/api/interceptor.ts
  webpack.config.js
Labels: ⚙️chore, 👩🏻‍💻 frontend

#221 chore: aws s3 배포 자동화를 위한 빌드 스크립트 생성
  .github/workflows/deploy.yml
  package.json
Labels: ⚙️chore, 👩🏻‍💻 frontend

#214 feat: 톡픽 비회원 투표 기능 구현
  src/components/molecules/LoginForm/LoginForm.tsx
  src/components/molecules/VotePrototype/VotePrototype.style.ts
  src/components/molecules/VotePrototype/VotePrototype.tsx
  src/components/organisms/CommentsSection/CommentsSection.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
  src/constants/message.ts
  src/hooks/login/useLoginForm.ts
  src/hooks/modal/useToastModal.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/TalkPickPage/TalkPickPage.tsx
  src/stories/molecules/VotePrototype.stories.tsx
  src/stories/organisms/TalkPickSection.stories.tsx
  src/types/talk-pick.ts
  src/types/vote.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#223 fix: 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: ⚙️chore, 👩🏻‍💻 frontend

#207 feat: 밸런스게임 생성 API 연동
  .gitignore
  src/App.tsx
  src/api/game.ts
  src/components/atoms/Button/Button.style.ts
  src/components/atoms/ChoiceInputButton/ChoiceInputButton.style.ts
  src/components/atoms/ChoiceInputButton/ChoiceInputButton.tsx
  src/components/atoms/ImageBoxButton/ImageBoxButton.tsx
  src/components/atoms/Input/Input.style.ts
  src/components/atoms/Input/Input.tsx
  src/components/atoms/Modal/Modal.style.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/BalanceGameOptionCard/BalanceGameOptionCard.style.ts
  src/components/molecules/BalanceGameOptionCard/BalanceGameOptionCard.tsx
  src/components/molecules/GameNavigationSection/GameNavigationSection.style.ts
  src/components/molecules/GameNavigationSection/GameNavigationSection.tsx
  src/components/molecules/TagModal/TagModal.style.ts
  src/components/molecules/TagModal/TagModal.tsx
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.style.ts
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.tsx
  src/components/organisms/Header/Header.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/file/useFileUploadMutation.ts
  src/hooks/api/game/useCreateBalanceGameMutation.ts
  src/hooks/api/game/useTempGameQuery.ts
  src/hooks/api/game/useTempGameSaveMutation.ts
  src/hooks/game/useBalanceGameCreation.ts
  src/hooks/game/useStageNavigation.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.style.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/stories/atoms/ChoiceInputButton.stories.tsx
  src/stories/atoms/Input.stories.tsx
  src/stories/atoms/Modal.stories.tsx
  src/stories/molecules/BalanceGameOptionCard.stories.tsx
  src/stories/molecules/GameNavigationSection.stories.tsx
  src/stories/molecules/TagModal.stories.tsx
  src/stories/organisms/BalanceGameCreation.stories.tsx
  src/styles/typo.ts
  src/types/game.ts
  src/utils/balanceGameUtils.ts
  src/utils/file.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#216 feat: 밸런스게임 비회원 투표 기능 구현
  src/components/molecules/BalanceGameBox/BalanceGameBox.tsx
  src/components/molecules/SearchGameList/SearchGameList.tsx
  src/components/organisms/BalanceGameSection/BalanceGameSection.tsx
  src/stories/molecules/BalanceGameBox.stories.tsx
  src/types/vote.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#229 refactor: 페이지네이션 및 밸런스게임 조회 페이지 북마크 리팩토링
  src/components/molecules/BalanceGameEndingBox/BalanceGameEndingBox.tsx
  src/components/molecules/LoginForm/LoginForm.style.ts
  src/components/molecules/LoginForm/LoginForm.tsx
  src/components/molecules/LoginModal/LoginModal.tsx
  src/components/organisms/BalanceGameSection/BalanceGameSection.tsx
  src/components/organisms/CommentsSection/CommentsSection.tsx
  src/components/organisms/TalkPickListSection/TalkPickListSection.tsx
  src/constants/message.ts
  src/hooks/api/like/useCreateLikeCommentMutation.ts
  src/hooks/api/member/useSignUpMutation.ts
  src/hooks/api/report/useReportCommentMutation.ts
  src/hooks/comment/useCommentActions.ts
  src/hooks/login/useLoginForm.ts
  src/pages/TalkPickPage/TalkPickPage.tsx
  src/pages/TalkPickPlacePage/TalkPickPlacePage.tsx
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend

#233 refactor: 검색결과 페이지 스켈레톤 적용
  src/components/atoms/SearchResultCardSkeleton/SearchResultCardSkeleton.style.ts
  src/components/atoms/SearchResultListSkeleton/SearchResultListSkeleton.style.ts
  src/components/organisms/SearchGameListSection/SearchGameListSection.tsx
  src/components/organisms/SearchGameResult/SearchGameResult.tsx
  src/components/organisms/SearchTalkPickListSection/SearchTalkPickListSection.tsx
  src/components/organisms/SearchTalkPickResult/SearchTalkPickResult.tsx
  src/pages/SearchResultsPage/SearchResultsPage.style.ts
  src/pages/SearchResultsPage/SearchResultsPage.tsx
  src/stories/organisms/SearchGameListSection.stories.tsx
  src/stories/organisms/SearchGameResult.stories.tsx
  src/stories/organisms/SearchTalkPickResult.stories.tsx
Labels: 👩🏻‍💻 frontend, 🪄refactor

#235 refactor: 밸런스 게임 제작 이미지 업로드 로직 수정
  src/assets/index.ts
  src/assets/svg/trash.svg
  src/components/atoms/ImageBoxButton/ImageBoxButton.style.ts
  src/components/atoms/ImageBoxButton/ImageBoxButton.tsx
  src/components/molecules/BalanceGameOptionCard/BalanceGameOptionCard.tsx
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.tsx
  src/hooks/api/game/useCreateBalanceGameMutation.ts
  src/hooks/game/useBalanceGameCreation.ts
  src/hooks/game/useStageNavigation.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/stories/atoms/ImageBoxButton.stories.tsx
  src/stories/molecules/BalanceGameOptionCard.stories.tsx
  src/stories/organisms/BalanceGameCreation.stories.tsx
  src/types/file.ts
  src/types/game.ts
  src/utils/balanceGameUtils.ts
Labels: 👩🏻‍💻 frontend, 🪄refactor

#237 bug: 배포 스크립트 실행 시 특정 모듈을 감지하지 못하는 문제
  .github/workflows/deploy.yml
  package-lock.json
  package.json
Labels: ⚙️chore, 🐛bug

#232 refactor: 톡픽 작성 코드 리팩토링
  package-lock.json
  package.json
  src/api/file.ts
  src/api/talk-pick.ts
  src/components/atoms/CitationBox/CitationBox.tsx
  src/components/atoms/ImageUploadButton/ImageUploadButton.tsx
  src/components/atoms/OptionInputBox/OptionInputBox.tsx
  src/components/molecules/ImageUploader/ImageUploader.tsx
  src/components/organisms/PostInputForm/PostInputForm.style.ts
  src/components/organisms/PostInputForm/PostInputForm.tsx
  src/constants/api.ts
  src/constants/message.ts
  src/hooks/api/file/useDeleteFileMutation.ts
  src/hooks/api/file/useFileUploadMutation.ts
  src/hooks/api/talk-pick/useCreateTalkPickMutation.ts
  src/hooks/api/talk-pick/useEditTalkPickMutation.ts
  src/hooks/api/talk-pick/useSaveTempTalkPickMutation.ts
  src/hooks/post/usePostTalkPickForm.ts
  src/hooks/post/useTalkPickInputs.ts
  src/hooks/post/validatePostForm.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/stories/atoms/ImageUploadButton.stories.tsx
  src/stories/molecules/ImageUploader.stories.tsx
  src/stories/organisms/PostInputForm.stories.tsx
  src/types/file.ts
  src/types/talk-pick.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🪄refactor

#239 chore: CI/CD 설정을 위한 빌드 스크립트 수정
  .github/workflows/deploy.yml
  package.json
Labels: ⚙️chore, 👩🏻‍💻 frontend
