Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-03, with the labels that each got.

#50 feat: 게시물의 댓글을 가져오는 기능 구현
  src/api/comments/comments.ts
  src/components/common/UserComment.tsx
  src/constants/api.ts
  src/mocks/data/comments.ts
  src/mocks/handlers/comments.ts
  src/mocks/handlers/handlers.ts
  src/pages/PostPage/CommentsSection/CommentsByOption/CommentsByOption.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/types/comment.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 💬 댓글 / 답글, 🪄 Mocking

#52 feat: 밸런스 게임 사진 선택지 클릭 시, 체크표시와 함께 결과 Section을 보여주는 기능 구현
  src/assets/index.ts
  src/assets/svg/check.svg
  src/assets/svg/winner.svg
  src/components/common/BalacneOptionCard.tsx
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/components/common/PostOptionCard.tsx
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/PostPage.style.ts
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/TitleSection/TitleSection.style.ts
  src/pages/PostPage/TitleSection/TitleSection.tsx
Labels: 💳 투표, 🪧 게시물

#48 refactor: 랜딩, 게시글, 게시글 작성 페이지 리팩토링
  src/components/CreatPostPage/CreatePostForm.tsx
  src/components/CreatPostPage/ImageDropZone.tsx
  src/components/LandingPage/Carousel.tsx
  src/components/LandingPage/MainPost.style.ts
  src/components/LandingPage/MainPost.tsx
  src/components/LandingPage/Pagination.tsx
  src/components/LandingPage/VoteButton.tsx
  src/components/PostListPage/CreatePostButton.tsx
  src/components/PostListPage/PostItem.style.ts
  src/components/PostListPage/PostItem.tsx
  src/components/PostListPage/PostItemImage.style.ts
  src/components/PostListPage/PostItemImage.tsx
  src/components/common/PostImage.tsx
  src/components/common/PostImage/PostImage.sylte.ts
  src/components/common/PostImage/PostImage.tsx
  src/constants/message.ts
  src/pages/CreatePostPage/CreatePostPage.style.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/LandingPage/LandingPage.style.ts
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LandingPage/sections/MainPost.tsx
  src/pages/PostListPage/PostListPage.style.ts
  src/pages/PostListPage/PostListPage.tsx
  src/pages/PostListPage/sections/PostItem.tsx
  src/pages/PostListPage/sections/PostItemImage.tsx
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup

#57 feat : 투표 시, 투표 결과를 보여주는 기능 구현
  src/api/posts/posts.ts
  src/assets/index.ts
  src/assets/svg/fight.svg
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/constants/api.ts
  src/mocks/handlers/post.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/styles/Theme.ts
  src/utils/calculator.ts
  tsconfig.json
  webpack.config.js
Labels: ⚙️chore, 👩🏻‍💻 frontend, 🪄refactor, 💳 투표

#59 fix: 새로고침 시 탭 활성화 문제 해결
  src/assets/svg/LeftButton.svg
  src/assets/svg/RightButton.svg
  src/hooks/mypage/userHistory/useTabChange.ts
  src/pages/MyPage/HistoryPage/HistoryPage.tsx
  src/pages/MyPage/sections/Sidebar/Sidebar.style.ts
  src/pages/MyPage/sections/Sidebar/Sidebar.tsx
  src/pages/MyPage/sections/Sidebar/SidebarTab/SidebarTab.style.ts
  src/pages/MyPage/sections/Sidebar/SidebarTab/SidebarTab.tsx
Labels: ✔︎pull requests, 🐛bug, 👩🏻‍💻 frontend

#62 Feat : 랜딩, 게시글, 게시글 작성 페이지 API 서버와 연결
  package.json
  src/api/interceptor.ts
  src/api/posts/posts.ts
  src/components/CreatPostPage/CreatePostForm.tsx
  src/components/CreatPostPage/ImageDropZone.tsx
  src/components/LandingPage/MainPost.tsx
  src/components/PostListPage/PostItem.tsx
  src/components/PostListPage/PostItemImage.style.ts
  src/components/PostListPage/PostItemImage.tsx
  src/components/common/PostImage/PostImage.sylte.ts
  src/components/common/PostImage/PostImage.tsx
  src/index.tsx
  src/mocks/handlers/post.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/types/post.ts
  webpack.config.js
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend

#64 fix: swagger 구조 변경으로 인한 mock data 변경
  src/api/posts/posts.ts
  src/mocks/data/posts.ts
Labels: ✔︎pull requests, 🐛bug

#67 feat: 댓글 목록 디자인 수정, 비회원/회원일 때 선택지 투표 및 변경하는 로직 구현
  src/api/comments/comments.ts
  src/api/posts/posts.ts
  src/api/votes/vote.ts
  src/assets/images/no-image.png
  src/assets/index.ts
  src/assets/svg/vote.svg
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/components/common/UserComment.tsx
  src/components/common/UserComment/UserComment.style.ts
  src/components/common/UserComment/UserComment.tsx
  src/constants/api.ts
  src/constants/pagination.ts
  src/hooks/login/useAuth.ts
  src/hooks/vote/useSelectedOptionsInLocalStorage.ts
  src/mocks/data/comments.ts
  src/mocks/data/posts.ts
  src/mocks/handlers/handlers.ts
  src/mocks/handlers/vote.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.style.ts
  src/pages/PostPage/CommentsSection/CommentsByOption/CommentsByOption.tsx
  src/pages/PostPage/CommentsSection/CommentsPagination/CommentsPagination.style.ts
  src/pages/PostPage/CommentsSection/CommentsPagination/CommentsPagination.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.style.ts
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/CreatorSection/CreatorSection.style.ts
  src/pages/PostPage/CreatorSection/CreatorSection.tsx
  src/pages/PostPage/PostPage.style.ts
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/TitleSection/TitleSection.style.ts
  src/pages/PostPage/TitleSection/TitleSection.tsx
  src/pages/PostPage/UserUtilitySection/UserUtilitySection.style.ts
  src/pages/PostPage/UserUtilitySection/UserUtilitySection.tsx
  src/types/comment.ts
  src/types/post.ts
  src/types/vote.ts
  src/utils/date.ts
Labels: 💳 투표, 🪧 게시물

#68 feat: 회원가입 관련 api들 연결
  src/api/HttpError.ts
  src/api/email/email.ts
  src/api/interceptor.ts
  src/api/member/duplicate.ts
  src/api/member/member.ts
  src/components/common/InputsUserInfo/InputCode.tsx
  src/components/common/InputsUserInfo/InputEmail.tsx
  src/components/common/InputsUserInfo/InputNickname.tsx
  src/components/common/InputsUserInfo/InputPw.tsx
  src/components/common/InputsUserInfo/InputPwCheck.tsx
  src/constants/api.ts
  src/constants/message.ts
  src/hooks/api/useSignUpMutation.ts
  src/hooks/common/inputsUserInfo/useCheckCode.ts
  src/hooks/common/inputsUserInfo/useCheckEmail.ts
  src/hooks/common/inputsUserInfo/useCheckNickname.ts
  src/hooks/common/inputsUserInfo/useCheckPassword.ts
  src/hooks/common/inputsUserInfo/useCheckPasswordCheck.ts
  src/hooks/common/useActiveSubmit.ts
  src/hooks/common/useFocusFalse.ts
  src/hooks/findPassword/useFindPwForm.ts
  src/hooks/signup/useSignupForm.ts
  src/pages/FindPasswordPage/FindPasswordPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/types/member.ts
  src/utils/validator.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature, 🙆‍♀️회원가입

#72 feat: 댓글 작성기능 구현, API 명세에 맞춰 타입 재정리
  src/api/comments/comments.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/components/common/InputComment/InputComment.tsx
  src/components/common/UserComment/UserComment.tsx
  src/constants/api.ts
  src/hooks/comment/useCreateComment.ts
  src/hooks/comment/useCreateCommentForm.ts
  src/hooks/common/useUserInfo.ts
  src/hooks/login/useAuth.ts
  src/mocks/data/comments.ts
  src/mocks/data/posts.ts
  src/mocks/handlers/comments.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/CommentsSection/CommentsPagination/CommentsPagination.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.style.ts
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/TitleSection/TitleSection.tsx
  src/types/comment.ts
  src/types/post.ts
  src/types/vote.ts
  src/utils/date.ts
Labels: 💬 댓글 / 답글

#73 feat: 게시물과 댓글에 좋아요, 신고 기능 구현 / 게시물에 북마크 기능 구현 / 로그인 여부를 묻는 모달 생성
  src/api/comments/comments.ts
  src/api/posts/posts.ts
  src/assets/index.ts
  src/assets/svg/report.svg
  src/assets/svg/share.svg
  src/assets/svg/star.svg
  src/components/Buttons/CommentLikeButton.tsx
  src/components/Buttons/CommentReportButton.tsx
  src/components/Buttons/PostBookmarkButton.tsx
  src/components/Buttons/PostLikeButton.tsx
  src/components/Buttons/PostReportButton.tsx
  src/components/common/Modal/LoginModal.style.ts
  src/components/common/Modal/LoginModal.tsx
  src/components/common/UserComment/UserComment.style.ts
  src/components/common/UserComment/UserComment.tsx
  src/constants/api.ts
  src/hooks/common/useUserInfo.ts
  src/mocks/data/comments.ts
  src/mocks/data/posts.ts
  src/mocks/handlers/comments.ts
  src/mocks/handlers/post.ts
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/PostPage.style.ts
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/UserUtilitySection/UserUtilitySection.style.ts
  src/pages/PostPage/UserUtilitySection/UserUtilitySection.tsx
  src/types/comment.ts
Labels: 💬 댓글 / 답글, ❗️신고, 👍 좋아요, ⭐️ 북마크

#74 feat: 로그인, 로그아웃 기능 구현
  package-lock.json
  package.json
  src/App.tsx
  src/api/historyPosts/historyPosts.ts
  src/api/interceptor.ts
  src/api/member/auth.ts
  src/api/member/member.ts
  src/components/common/Profile/Profile.style.ts
  src/components/common/Profile/Profile.tsx
  src/constants/api.ts
  src/hooks/api/useLogoutMutation.ts
  src/hooks/api/useMemberQuery.ts
  src/hooks/api/useMyBookmarksPostsQuery.ts
  src/hooks/common/inputsUserInfo/useCheckCode.ts
  src/hooks/common/inputsUserInfo/useCheckEmail.ts
  src/hooks/common/useParseJwt.ts
  src/hooks/common/useTokenRefresh.ts
  src/hooks/login/useLoginForm.ts
  src/index.tsx
  src/layout/Header.tsx
  src/layout/Header/Header.style.ts
  src/layout/Header/Header.tsx
  src/layout/Header/Login/Login.tsx
  src/layout/Header/Logout/Logout.tsx
  src/layout/layout.tsx
  src/pages/LoginPage/sections/LoginForm/LoginForm.tsx
  src/pages/MyPage/HistoryPage/TabPage/BookmarksPage/BookmarksPage.tsx
  src/store/auth.ts
  src/store/index.ts
  src/styles/Theme.ts
  src/types/member.ts
Labels: ⚙️chore, ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature, 🗝️로그인, ℹ️마이페이지

#78 feat : 투표 로직 수정, 댓글 및 답글 주요 기능(조회, 생성, 삭제, 좋아요 추가/취소, 신고) 구현
  public/defaultImage.png
  src/api/comments/comments.ts
  src/api/posts/posts.ts
  src/assets/index.ts
  src/assets/svg/Delete.svg
  src/assets/svg/Edit.svg
  src/components/Buttons/CommentDeleteButton.tsx
  src/components/Buttons/CommentEditButton.tsx
  src/components/Buttons/CommentLikeButton.tsx
  src/components/Buttons/CommentReportButton.tsx
  src/components/Buttons/PostBookmarkButton.tsx
  src/components/Buttons/PostLikeButton.tsx
  src/components/Buttons/PostReportButton.tsx
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/components/common/InputComment/InputEditedComment/InputEditedComment.tsx
  src/components/common/InputComment/InputNewComment/InputNewComment.tsx
  src/components/common/InputComment/InputNewReply/InputNewReply.tsx
  src/components/common/Modal/ChangeVoteModal/ChangeVoteModal.style.ts
  src/components/common/Modal/ChangeVoteModal/ChangeVoteModal.tsx
  src/components/common/Modal/LoginModal/LoginModal.style.ts
  src/components/common/Modal/LoginModal/LoginModal.tsx
  src/components/common/UserComment/UserComment.style.ts
  src/components/common/UserComment/UserComment.tsx
  src/constants/api.ts
  src/constants/pagination.ts
  src/hooks/comment/useCreateReply.ts
  src/hooks/comment/useEditComment.ts
  src/hooks/comment/useEditCommentForm.ts
  src/hooks/common/useUserInfo.ts
  src/hooks/vote/useSelectedOptionsInLocalStorage.ts
  src/mocks/data/comments.ts
  src/mocks/data/posts.ts
  src/mocks/handlers/comments.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/CommentsSection/CommentSection/CommentSection.tsx
  src/pages/PostPage/CommentsSection/CommentSection/RepliesSection/RepliesSection.style.ts
  src/pages/PostPage/CommentsSection/CommentSection/RepliesSection/RepliesSection.tsx
  src/pages/PostPage/CommentsSection/CommentsPagination/CommentsPagination.style.ts
  src/pages/PostPage/CommentsSection/CommentsPagination/CommentsPagination.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.style.ts
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/CreatorSection/CreatorSection.style.ts
  src/pages/PostPage/CreatorSection/CreatorSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/TitleSection/TitleSection.tsx
  src/types/comment.ts
  src/types/post.ts
  src/types/vote.ts
  src/utils/date.ts
  webpack.config.js
Labels: 💳 투표, 💬 댓글 / 답글, ❗️신고, ⭐️ 북마크

#80 feat: 회원정보 수정, 탈퇴, 비밀번호 찾기 기능 구현, api 변경에 따른 추가 수정 작업
  src/api/email/email.ts
  src/api/file/file.ts
  src/api/member/auth.ts
  src/api/member/member.ts
  src/components/common/InputsUserInfo/InputEmail.tsx
  src/components/common/InputsUserInfo/InputNickname.tsx
  src/components/common/InputsUserInfo/InputProfileImage/InputProfileImage.tsx
  src/components/common/InputsUserInfo/InputPw.tsx
  src/components/common/InputsUserInfo/InputPwCheck.tsx
  src/components/common/Profile/Profile.tsx
  src/components/design/Button/Button.style.ts
  src/constants/api.ts
  src/constants/input.ts
  src/hooks/api/useLogoutMutation.ts
  src/hooks/api/useMemberImageMutation.ts
  src/hooks/api/useMemberNicknameMutation.ts
  src/hooks/api/useMemberPwMutation.ts
  src/hooks/common/inputsUserInfo/useCheckEmail.ts
  src/hooks/common/useTokenRefresh.ts
  src/hooks/login/useLoginForm.ts
  src/hooks/mypage/memberDelete/useMemberDelete.ts
  src/hooks/mypage/memberUpdate/useMemberUpdate.ts
  src/hooks/mypage/userDelete/useUserDelete.ts
  src/hooks/mypage/userUpdate/useUserUpdate.ts
  src/hooks/signup/useSignupForm.ts
  src/pages/FindPasswordPage/FindPasswordPage.tsx
  src/pages/MyPage/DeletePage/DeletePage.tsx
  src/pages/MyPage/DeletePage/sections/DeleteForm/DeleteForm.style.ts
  src/pages/MyPage/DeletePage/sections/DeleteForm/DeleteForm.tsx
  src/pages/MyPage/UpdatePage/UpdatePage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/types/member.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature, 🙆‍♀️회원가입, ℹ️마이페이지

#81 feat: 투표 후, 득표수가 더 많은 선택지에 메달 이미지를 보여주는 기능 구현
  src/api/comments/comments.ts
  src/assets/index.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/components/common/Modal/ChangeVoteModal/ChangeVoteModal.style.ts
  src/components/common/Modal/LoginModal/LoginModal.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.tsx
  src/pages/PostPage/CommentsSection/CommentSection/RepliesSection/RepliesSection.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/PostPage.style.ts
  src/pages/PostPage/PostPage.tsx
  src/types/comment.ts
Labels: 💳 투표

#83 feat: 기타 기능 구현
  dist/bundle.js
  src/api/posts/posts.ts
  src/components/Buttons/HeartButton.tsx
  src/components/CreatPostPage/CreatePostForm.tsx
  src/components/LandingPage/MainPost.style.ts
  src/components/LandingPage/MainPost.tsx
  src/components/PostListPage/PostItem.style.ts
  src/components/PostListPage/PostItem.tsx
  src/components/Routes/ProtectedRoutes.tsx
  src/components/common/PostImage/PostImage.sylte.ts
  src/components/common/PostImage/PostImage.tsx
  src/layout/Header/Header.style.ts
  src/layout/Header/Header.tsx
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/LandingPage/LandingPage.tsx
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend

#90 fix: 태그 추가에서 한글 입력시 마지막 글자 두 번 입력되는 버그 수정
  src/components/Buttons/HeartButton.tsx
  src/pages/CreatePostPage/CreatePostPage.tsx
Labels: ✔︎pull requests, 🐛bug, 👩🏻‍💻 frontend

#91 feat: 마이페이지 활동 내역 조회 기능 구현
  src/api/email/email.ts
  src/api/historyPosts/historyPosts.ts
  src/api/member/member.ts
  src/api/mypage/mypage.ts
  src/components/common/InputsUserInfo/InputProfileImage/InputProfileImage.tsx
  src/components/common/Profile/Profile.tsx
  src/components/mypage/ListItem/ItemMyBookmarksPosts.tsx
  src/components/mypage/ListItem/ItemMyCommentsPosts.tsx
  src/components/mypage/ListItem/ItemMyPosts.tsx
  src/components/mypage/ListItem/ItemMyVotedPosts.tsx
  src/components/mypage/ListItem/ItemNull.tsx
  src/constants/api.ts
  src/hooks/api/useBookmarkDeleteAllMutation.ts
  src/hooks/api/useMyBookmarksPostsQuery.ts
  src/hooks/api/useMyCommentsPostsQuery.ts
  src/hooks/api/useMyPostsQuery.ts
  src/hooks/api/useMyVotedPostsQuery.ts
  src/hooks/common/inputsUserInfo/useCheckEmail.ts
  src/hooks/mypage/userHistory/useCheckboxSelect.ts
  src/mocks/data/history.ts
  src/pages/MyPage/HistoryPage/TabPage/BookmarksPage/BookmarksPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/CommentsPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/PostsPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/VotedPostsPage.tsx
  src/pages/MyPage/UpdatePage/UpdatePage.tsx
  src/types/history.ts
  src/types/member.ts
  src/types/mypage.ts
  src/types/pagination.ts
  src/utils/array.ts
  src/utils/date.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature, ℹ️마이페이지
