Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-04, with the labels that each got.

#95 feat : 테스트 시나리오에서 발견된 버그 및 기능 수정
  src/api/comments/comments.ts
  src/api/posts/posts.ts
  src/assets/index.ts
  src/assets/svg/Closed.svg
  src/components/Buttons/CommentDeleteButton.tsx
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/BalanceOptionCard/BalanceOptionCard.tsx
  src/components/common/Modal/DeleteCommentModal/DeleteCommentModal.style.ts
  src/components/common/Modal/DeleteCommentModal/DeleteCommentModal.tsx
  src/components/common/UserComment/UserComment.tsx
  src/constants/api.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/BalanceOptionCardsSection.tsx
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.style.ts
  src/pages/PostPage/BalanceOptionCardsSection/ResultSection/ResultSection.tsx
  src/pages/PostPage/CommentsSection/CommentsSection.tsx
  src/pages/PostPage/PostPage.style.ts
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/TitleSection/TitleSection.style.ts
  src/pages/PostPage/TitleSection/TitleSection.tsx
  src/types/comment.ts
  src/utils/date.ts
Labels: 🪧 게시글 본문

#97 fix: 게시물 및 댓글 신고 시 발생하는 400 에러 수정
  src/api/comments/comments.ts
  src/api/posts/posts.ts
Labels: ❗️신고

#99 feat: 게시물 삭제 전 확인 모달 창 띄우기
  dist/bundle.js
  src/components/mypage/ListItem/ItemMyPosts.tsx
Labels: ✨feature, 👩🏻‍💻 frontend

#101 fix: 회원 및 마이페이지 관련 에러 사항 수정
  src/App.tsx
  src/api/interceptor.ts
  src/constants/message.ts
  src/hooks/common/inputsUserInfo/useCheckPassword.ts
  src/hooks/common/useTokenRefresh.ts
  src/pages/NotFoundPage/NotFoundPage.style.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/utils/validator.ts
Labels: 👩🏻‍💻 frontend, 🪄refactor, 🙆‍♀️회원가입, ℹ️마이페이지

#103 feat: 프로필 사진 클릭 시, 프로필 모달을 보여주는 기능 구현
  src/components/common/BalanceOptionCard/BalanceOptionCard.style.ts
  src/components/common/Modal/ProfileModal/ProfileModal.style.ts
  src/components/common/Modal/ProfileModal/ProfileModal.tsx
  src/components/common/UserComment/UserComment.style.ts
  src/components/common/UserComment/UserComment.tsx
  src/pages/PostPage/CreatorSection/CreatorSection.style.ts
  src/pages/PostPage/CreatorSection/CreatorSection.tsx
  src/pages/PostPage/PostPage.tsx
  src/pages/PostPage/TitleSection/TitleSection.tsx
  src/types/comment.ts
  src/types/post.ts
Labels: 🪧 게시글 본문, 👤 프로필

#106 feat : 신고 이력이 있거나 본인이 작성한 게시글/댓글의 신고 버튼을 눌렀을 때, 신고가 불가함을 알려주는 기능 구현
  src/components/Buttons/CommentReportButton.tsx
  src/components/Buttons/PostReportButton.tsx
  src/components/common/Modal/ReportModal/ReportModal.tsx
  src/components/common/UserComment/UserComment.tsx
  src/pages/PostPage/UserUtilitySection/UserUtilitySection.tsx
Labels: ❗️신고, 🪧 게시글 본문

#108 fix: 비회원 상태일 때, 프로필 조회 시 발생하는 401 에러 해결
  src/api/member/member.ts
  src/components/common/Modal/ProfileModal/ProfileModal.tsx
  src/constants/api.ts
  src/hooks/api/useMemberProfileQuery.ts
Labels: 🪧 게시글 본문, 👤 프로필

#111 fix: 게시글 전체 조회 버그 및 북마크한 게시글 중복 버그 수정
  package-lock.json
  package.json
  src/api/posts/posts.ts
  src/assets/images/logo.png
  src/components/Buttons/ToggleButton.tsx
  src/components/PostListPage/PostItem.tsx
  src/layout/Header/Header.style.ts
  src/layout/Header/Header.tsx
  src/layout/SearchBar.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/BookmarksPage/BookmarksPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/CommentsPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/PostsPage.tsx
  src/pages/MyPage/HistoryPage/TabPage/VotedPostsPage.tsx
  src/pages/PostListPage/PostListPage.style.ts
  src/pages/PostListPage/PostListPage.tsx
  src/types/post.ts
Labels: ✔︎pull requests, 🐛bug, 👩🏻‍💻 frontend, ℹ️마이페이지
