Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-09, with the labels that each got.

#177 design: 회원가입 기본 이미지 팝업 UI 구현
  src/assets/images/eel-profile.png
  src/assets/images/jellyfish-profile.png
  src/assets/images/octopus-profile.png
  src/assets/images/rabbit-profile.png
  src/assets/images/ray-profile.png
  src/assets/images/turtle-profile.png
  src/assets/index.ts
  src/components/atoms/Modal/Modal.style.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/DefaultProfileModal/DefaultProfileModal.style.ts
  src/components/molecules/DefaultProfileModal/DefaultProfileModal.tsx
  src/stories/atoms/Modal.stories.tsx
  src/stories/molecules/DefaultProfileModal.stories.tsx
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup

#174 design: 검색 결과 Page 톡픽 UI 구현
  src/components/atoms/SearchTalkPickItem/SearchTalkPickItem.style.ts
  src/components/atoms/SearchTalkPickItem/SearchTalkPickItem.tsx
  src/components/molecules/SearchTalkPickList/SearchTalkPickList.style.ts
  src/components/molecules/SearchTalkPickList/SearchTalkPickList.tsx
  src/components/organisms/SearchTalkPickListSection/SearchTalkPickListSection.style.ts
  src/components/organisms/SearchTalkPickListSection/SearchTalkPickListSection.tsx
  src/stories/atoms/SearchTalkPickItem.stories.tsx
  src/stories/molecules/SearchTalkPickList.stories.tsx
  src/stories/organisms/SearchTalkPickListSection.stories.tsx
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup

#181 feat: 회원가입 api 연결 및 동작 처리 구현
  src/api/email.ts
  src/api/member.ts
  src/components/molecules/InputProfileImage/InputProfileImage.style.ts
  src/components/molecules/InputProfileImage/InputProfileImage.tsx
  src/components/molecules/InputPw/InputPw.tsx
  src/components/molecules/InputPwCheck/InputPwCheck.tsx
  src/constants/image.ts
  src/hooks/api/member/useSignUpMutation.ts
  src/hooks/common/inputsUserInfo/useCheckEmail.ts
  src/hooks/common/inputsUserInfo/useCheckNickname.ts
  src/hooks/common/inputsUserInfo/useCheckPassword.ts
  src/hooks/common/inputsUserInfo/useCheckPasswordCheck.ts
  src/hooks/common/inputsUserInfo/useCheckProfileImage.ts
  src/hooks/signup/useSignupForm.ts
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/types/member.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature, 🙆‍♀️회원가입

#183 feat: 알림 api 연결 및 4차 컴포넌트 UI 구현
  package-lock.json
  package.json
  src/api/notifications.ts
  src/components/atoms/BalanceGameButton/BalanceGameButton.style.ts
  src/components/atoms/BalanceGameButton/BalanceGameButton.tsx
  src/components/atoms/NoResultsMessage/NoResultsMessage.style.ts
  src/components/atoms/NoResultsMessage/NoResultsMessage.tsx
  src/components/atoms/NotificationItem/NotificationItem.tsx
  src/components/atoms/SubTag/SubTag.style.ts
  src/components/atoms/SubTag/SubTag.tsx
  src/components/atoms/TitleDescriptionField/TitleDescriptionField.style.ts
  src/components/atoms/TitleDescriptionField/TitleDescriptionField.tsx
  src/components/molecules/BalanceGameBox/BalanceGameBox.style.ts
  src/components/molecules/BalanceGameBox/BalanceGameBox.tsx
  src/components/molecules/Notification/Notification.tsx
  src/components/organisms/Header/Header.tsx
  src/constants/message.ts
  src/stories/atoms/BalanceGameButton.stories.tsx
  src/stories/atoms/NoResultsMessage.stories.tsx
  src/stories/atoms/SubTag.stories.tsx
  src/stories/atoms/TitleDescriptionField.stories.tsx
  src/stories/molecules/BalanceGameBox.stories.tsx
  tsconfig.json
Labels: ✔︎pull requests, 🐛bug, 👩🏻‍💻 frontend, 🎨 markup

#184 design: 검색 결과 페이지, 4차 추가 UI 구현
  src/assets/images/test-image.png
  src/assets/index.ts
  src/assets/svg/bookmark-df.svg
  src/assets/svg/share.svg
  src/components/atoms/ImageBoxButton/ImageBoxButton.style.ts
  src/components/atoms/ImageBoxButton/ImageBoxButton.tsx
  src/components/atoms/InteractionButton/InteractionButton.style.ts
  src/components/atoms/InteractionButton/InteractionButton.tsx
  src/components/atoms/Modal/Modal.style.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/ReportModal/ReportModal.tsx
  src/components/molecules/TextModal/TextModal.tsx
  src/stories/atoms/ImageBoxButton.stories.tsx
  src/stories/atoms/InteractionButton.stories.tsx
  src/stories/atoms/Modal.stories.tsx
  src/styles/typo.ts
Labels: 👩🏻‍💻 frontend, 😓help wanted, 🎨 markup
