Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-10, with the labels that each got.

#189 feat: 2차 페이지 관련 로직 추가 구현
  src/App.tsx
  src/components/atoms/TalkPickItem/TalkPickItem.style.ts
  src/components/atoms/TalkPickItem/TalkPickItem.tsx
  src/components/molecules/TopBanner/TodayTalkPickBanner/TodayTalkPickBanner.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.style.ts
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
  src/hooks/login/useLoginForm.ts
  src/pages/TalkPickPage/TalkPickPage.style.ts
  src/pages/TalkPickPage/TalkPickPage.tsx
  src/stories/atoms/TalkPickItem.stories.tsx
  src/stories/molecules/BestTalkPick.stories.tsx
  src/stories/molecules/TalkPickList.stories.tsx
  src/stories/organisms/TalkPickSection.stories.tsx
Labels: ✨feature, 👩🏻‍💻 frontend

#194 톡픽 작성, 톡앤픽 플레이스, 로그인 페이지 플로우 개선
  src/assets/index.ts
  src/assets/svg/option-error.svg
  src/components/atoms/Input/Input.style.ts
  src/components/atoms/OptionInputBox/OptionInputBox.style.ts
  src/components/atoms/OptionInputBox/OptionInputBox.tsx
  src/components/atoms/PostTitleBox/PostTitleBox.tsx
  src/components/atoms/SocialLoginButton/SocialLoginButton.style.ts
  src/components/atoms/TalkPickItem/TalkPickItem.style.ts
  src/components/molecules/ImageUploader/ImageUploader.tsx
  src/components/molecules/LoginForm/LoginForm.tsx
  src/components/molecules/LoginForm/LoginFrom.style.ts
  src/components/organisms/PostInputForm/PostInputForm.style.ts
  src/components/organisms/PostInputForm/PostInputForm.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
  src/constants/message.ts
  src/hooks/login/useLoginForm.ts
  src/pages/TalkPickPage/TalkPickPage.tsx
  src/stories/atoms/OptionInputBox.stories.tsx
  src/utils/validatePostForm.ts
  src/utils/validator.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup, ✅feature

#199 feat: 메인페이지 플로우 개선
  src/api/game.ts
  src/api/notifications.ts
  src/assets/index.ts
  src/assets/svg/arrow-down.svg
  src/assets/svg/arrow-up.svg
  src/assets/svg/bookmark-df.svg
  src/assets/svg/bookmark-pr.svg
  src/assets/svg/pick-vote.svg
  src/assets/svg/random-game.svg
  src/assets/svg/today-pick.svg
  src/components/atoms/CreateDropdown/CreateDropdown.style.ts
  src/components/atoms/CreateDropdown/CreateDropdown.tsx
  src/components/atoms/NotificationItem/NotificationItem.style.ts
  src/components/atoms/NotificationItem/NotificationItem.tsx
  src/components/molecules/CategoryBar/CategoryBar.tsx
  src/components/molecules/CategoryBox/CategoryBox.tsx
  src/components/molecules/ContentsButton/ContentsButton.tsx
  src/components/molecules/Notification/Notification.style.ts
  src/components/molecules/Notification/Notification.tsx
  src/components/organisms/BalanceGameList/BalanceGameList.tsx
  src/components/organisms/Header/Header.style.ts
  src/components/organisms/Header/Header.tsx
  src/components/organisms/MyBalanceGameList/MyBalanceGameList.tsx
  src/constants/api.ts
  src/hooks/api/game/useBestGameListQuery.ts
  src/hooks/api/game/useLatestGameListQuery.ts
  src/layout/layout.tsx
  src/pages/LandingPage/LandingPage.style.ts
  src/pages/LandingPage/LandingPage.tsx
  src/stories/atoms/CreateDropdown.stories.tsx
  src/stories/atoms/NotificationItem.stories.tsx
  src/stories/molecules/CategoryBar.stories.tsx
  src/stories/molecules/ContentsButton.stories.tsx
  src/stories/molecules/Notification.stories.tsx
  src/stories/organisms/BalanceGameList.stories.tsx
  src/types/game.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🎨 markup

#200 feat: 밸런스 게임 페이지 ui 구현 및 조회, 투표, 북마크 api 연결
  src/App.tsx
  src/api/bookmarks.ts
  src/api/game.ts
  src/api/vote.ts
  src/assets/gif/game-ending.gif
  src/assets/images/blue-game-bg.png
  src/assets/images/forest-game-bg.png
  src/assets/images/gray-game-bg.png
  src/assets/images/green-game-bg.png
  src/assets/images/pink-game-bg.png
  src/assets/images/purple-game-bg.png
  src/assets/index.ts
  src/assets/svg/next-arrow.svg
  src/assets/svg/prev-arrow.svg
  src/components/atoms/BalanceGameButton/BalanceGameButton.style.ts
  src/components/atoms/BalanceGameButton/BalanceGameButton.tsx
  src/components/atoms/Chips/Chips.style.ts
  src/components/atoms/Chips/Chips.tsx
  src/components/molecules/BalanceGameBox/BalanceGameBox.style.ts
  src/components/molecules/BalanceGameBox/BalanceGameBox.tsx
  src/components/molecules/BalanceGameEndingBox/BalanceGameEndingBox.style.ts
  src/components/molecules/BalanceGameEndingBox/BalanceGameEndingBox.tsx
  src/components/organisms/BalanceGameEndingSection/BalanceGameEndingSection.style.ts
  src/components/organisms/BalanceGameEndingSection/BalanceGameEndingSection.tsx
  src/components/organisms/BalanceGameSection/BalanceGameSection.style.ts
  src/components/organisms/BalanceGameSection/BalanceGameSection.tsx
  src/constants/api.ts
  src/constants/message.ts
  src/hooks/api/bookmark/useCreateDoneGameBookmark.ts
  src/hooks/api/bookmark/useCreateGameBookmarkMutation.ts
  src/hooks/api/bookmark/useDeleteDoneGameBookmark.ts
  src/hooks/api/bookmark/useDeleteGameBookmarkMutation.ts
  src/hooks/api/game/useGameByIdQuery.ts
  src/hooks/api/game/useGameBySetIdQuery.ts
  src/hooks/api/vote/useCreateGameVoteMutation.ts
  src/hooks/api/vote/useDeleteGameVoteMutation.ts
  src/hooks/api/vote/useEditGameVoteMutation.ts
  src/hooks/api/vote/useGameVoteQuery.ts
  src/hooks/modal/useToastModal.ts
  src/pages/BalanceGamePage/BalanceGamePage.style.ts
  src/pages/BalanceGamePage/BalanceGamePage.tsx
  src/stories/atoms/BalanceGameButton.stories.tsx
  src/stories/atoms/Chips.stories.tsx
  src/stories/molecules/BalanceGameBox.stories.tsx
  src/stories/molecules/BalanceGameEndingBox.stories.tsx
  src/stories/organisms/BalanceGameEndingSection.stories.tsx
  src/stories/organisms/BalanceGameSection.stories.tsx
  src/types/custom.d.ts
  src/types/game.ts
  src/utils/calculator.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup, ✅feature
