Repository JECT-Study/PICK-O-Client, pull requests merged in 2024-12, with the labels that each got.

#242 feat: 밸런스 게임 임시 저장
  src/api/game.ts
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.tsx
  src/hooks/api/file/useFileUploadMutation.ts
  src/hooks/api/game/useLoadTempGameQuery.ts
  src/hooks/api/game/useSaveTempGameMutation.ts
  src/hooks/api/game/useTempGameSaveMutation.ts
  src/hooks/game/useBalanceGameCreation.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.style.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/stories/organisms/BalanceGameCreation.stories.tsx
  src/types/game.ts
  src/utils/balanceGameUtils.ts
Labels: 👩🏻‍💻 frontend, ✅feature

#243 refactor: 밸런스게임 생성 관련 제약조건 추가
  src/components/atoms/ImageBoxButton/ImageBoxButton.style.ts
  src/components/atoms/TitleDescriptionField/TitleDescriptionField.style.ts
  src/components/atoms/TitleDescriptionField/TitleDescriptionField.tsx
  src/hooks/api/game/useCreateBalanceGameMutation.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/utils/imageUtils.ts
Labels: 👩🏻‍💻 frontend, 🪄refactor

#247 feat: 랜딩페이지 주제별 밸런스 게임 조회 api 수정
  src/api/game.ts
  src/components/organisms/BalanceGameList/BalanceGameList.tsx
  src/constants/api.ts
  src/constants/game.ts
  src/constants/message.ts
  src/pages/LandingPage/LandingPage.tsx
Labels: ✨feature, 👩🏻‍💻 frontend

#244 feat: 회원 정보 수정 페이지 ui 구현 및 api 연결
  src/App.tsx
  src/api/friends.ts
  src/api/member.ts
  src/components/Routes/ProtectedRoutes.tsx
  src/components/atoms/CommentProfile/CommentProfile.tsx
  src/components/atoms/TalkPickItem/TalkPickItem.tsx
  src/components/molecules/DefaultProfileModal/DefaultProfileModal.tsx
  src/components/molecules/InputInfoEmail/InputInfoEmail.style.ts
  src/components/molecules/InputInfoEmail/InputInfoEmail.tsx
  src/components/molecules/InputInfoNickname/InputInfoNickname.style.ts
  src/components/molecules/InputInfoNickname/InputInfoNickname.tsx
  src/components/molecules/InputInfoPw/InputInfoPw.style.ts
  src/components/molecules/InputInfoPw/InputInfoPw.tsx
  src/components/molecules/InputProfileImage/InputProfileImage.tsx
  src/components/molecules/LoginForm/LoginForm.tsx
  src/components/molecules/TopBanner/TodayTalkPickBanner/TodayTalkPickBanner.tsx
  src/components/organisms/Header/Header.tsx
  src/components/organisms/TalkPickListSection/TalkPickListSection.tsx
  src/constants/api.ts
  src/constants/message.ts
  src/constants/path.ts
  src/hooks/api/file/useFileUploadMutation.ts
  src/hooks/api/friends/useCreateFriendsMutation.ts
  src/hooks/api/friends/useFriendsListQuery.ts
  src/hooks/api/member/useChangeUserInfoMutation.ts
  src/hooks/api/talk-pick/useCreateTalkPickMutation.ts
  src/hooks/api/talk-pick/useDeleteTalkPickMutation.ts
  src/hooks/api/talk-pick/useEditTalkPickMutation.ts
  src/hooks/changeUserInfo/useChangeUserInfoForm.ts
  src/hooks/common/inputsUserInfo/useCheckNicknameChanged.ts
  src/hooks/common/inputsUserInfo/useCheckPasswordVerify.ts
  src/hooks/common/inputsUserInfo/useCheckProfileImage.ts
  src/hooks/login/useLoginForm.ts
  src/hooks/modal/useToastModal.ts
  src/hooks/signup/useSignupForm.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.style.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/pages/ChangeUserInfoPage/ChangeUserInfoPage.style.ts
  src/pages/ChangeUserInfoPage/ChangeUserInfoPage.tsx
  src/pages/CreatePostPage/CreatePostPage.style.ts
  src/pages/CreatePostPage/CreatePostPage.tsx
  src/pages/SignUpPage/SignUpPage.tsx
  src/stories/molecules/DefaultProfileModal.stories.tsx
  src/types/file.ts
  src/types/friends.ts
  src/types/member.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🎨 markup, ✅feature

#250 refactor: 임시 저장 api 보완
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.style.ts
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.tsx
  src/constants/message.ts
  src/hooks/api/game/useCreateBalanceGameMutation.ts
  src/hooks/api/game/useSaveTempGameMutation.ts
  src/hooks/game/useBalanceGameCreation.ts
  src/hooks/game/useStageNavigation.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/types/game.ts
  src/utils/balanceGameUtils.ts
Labels: 👩🏻‍💻 frontend, 🪄refactor

#257 hotfix: 잘못 처리된 괄호 처리 에러
  src/constants/message.ts
Labels: 🐛bug

#251 feat: 소셜 로그인 구현
  src/App.tsx
  src/constants/path.ts
  src/hooks/api/member/useLogoutMutation.ts
  src/hooks/common/useTokenRefresh.ts
  src/hooks/login/useLoginForm.ts
  src/utils/cookie.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🗝️로그인

#253 design: 모바일 컴포넌트 ui 구현
  src/assets/index.ts
  src/assets/svg/mobile-bookmark-df.svg
  src/assets/svg/mobile-bookmark-pr.svg
  src/assets/svg/mobile-check-icon.svg
  src/assets/svg/mobile-folder-check.svg
  src/assets/svg/mobile-folder.svg
  src/assets/svg/mobile-modal-close.svg
  src/assets/svg/mobile-share.svg
  src/assets/svg/mobile-temp-icon.svg
  src/components/atoms/CheckBoxButton/CheckBoxButton.style.ts
  src/components/mobile/atoms/Button/Button.style.ts
  src/components/mobile/atoms/Button/Button.tsx
  src/components/mobile/atoms/GameStageLabel/GameStageLabel.style.ts
  src/components/mobile/atoms/GameStageLabel/GameStageLabel.tsx
  src/components/mobile/atoms/GameTag/GameTag.style.ts
  src/components/mobile/atoms/GameTag/GameTag.tsx
  src/components/mobile/atoms/GameTagChip/GameTagChip.style.ts
  src/components/mobile/atoms/GameTagChip/GameTagChip.tsx
  src/components/mobile/atoms/IconButton/IconButton.style.ts
  src/components/mobile/atoms/IconButton/IconButton.tsx
  src/components/mobile/atoms/InteractionButton/InteractionButton.style.ts
  src/components/mobile/atoms/InteractionButton/InteractionButton.tsx
  src/components/mobile/atoms/Modal/Modal.style.ts
  src/components/mobile/atoms/Modal/Modal.tsx
  src/components/mobile/atoms/TempGameButton/TempGameButton.style.ts
  src/components/mobile/atoms/TempGameButton/TempGameButton.tsx
  src/components/mobile/atoms/TitleDescriptionField/TitleDescriptionField.style.ts
  src/components/mobile/atoms/TitleDescriptionField/TitleDescriptionField.tsx
  src/components/mobile/molecules/GameTagModal/GameTagModal.style.ts
  src/components/mobile/molecules/GameTagModal/GameTagModal.tsx
  src/components/mobile/molecules/ShareModal/ShareModal.style.ts
  src/components/mobile/molecules/ShareModal/ShareModal.tsx
  src/components/mobile/molecules/TempGameModal/TempGameModal.style.ts
  src/components/mobile/molecules/TempGameModal/TempGameModal.tsx
  src/components/molecules/ReportModal/ReportModal.style.ts
  src/components/molecules/TopBanner/TopBanner.style.ts
  src/stories/mobile/atoms/Button.stories.tsx
  src/stories/mobile/atoms/GameStageLabel.stories.tsx
  src/stories/mobile/atoms/GameTag.stories.tsx
  src/stories/mobile/atoms/GameTagChip.stories.tsx
  src/stories/mobile/atoms/IconButton.stories.tsx
  src/stories/mobile/atoms/InteractionButton.stories.tsx
  src/stories/mobile/atoms/Modal.stories.tsx
  src/stories/mobile/atoms/TempGameButton.stories.tsx
  src/stories/mobile/atoms/TitleDescriptionField.stories.tsx
  src/stories/mobile/molecules/GameTagModal.stories.tsx
  src/stories/mobile/molecules/ShareModal.stories.tsx
  src/stories/mobile/molecules/TempGameModal.stories.tsx
  src/styles/color.ts
  src/styles/typo.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup

#264 refactor: 변경된 밸런스게임 조회 api 파라미터 수정
  src/api/game.ts
  src/hooks/api/game/useBestGameListQuery.ts
  src/hooks/api/game/useLatestGameListQuery.ts
  src/pages/LandingPage/LandingPage.tsx
  src/types/game.ts
Labels: 👩🏻‍💻 frontend, 🪄refactor

#265 refactor: 검색 결과 페이지 리팩토링
  src/components/atoms/CategoryButton/CategoryButton.style.ts
  src/components/atoms/SearchBar/SearchBar.tsx
  src/components/atoms/SearchTalkPickItem/SearchTalkPickItem.style.ts
  src/components/atoms/SearchTalkPickItem/SearchTalkPickItem.tsx
  src/components/molecules/ContentsButton/ContentsButton.style.ts
  src/components/molecules/SearchGameList/SearchGameList.tsx
  src/components/molecules/SearchTalkPickList/SearchTalkPickList.tsx
  src/components/molecules/VotePrototype/VotePrototype.style.ts
  src/components/molecules/VotePrototype/VotePrototype.tsx
  src/components/organisms/SearchGameListSection/SearchGameListSection.tsx
  src/components/organisms/SearchGameResult/SearchGameResult.tsx
  src/components/organisms/SearchTalkPickListSection/SearchTalkPickListSection.tsx
  src/components/organisms/SearchTalkPickResult/SearchTalkPickResult.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.style.ts
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
  src/constants/api.ts
  src/hooks/search/usePagination.ts
  src/pages/SearchResultsPage/SearchGamePage.tsx
  src/pages/SearchResultsPage/SearchTalkPickPage.tsx
  src/pages/TalkPickPlacePage/TalkPickPlacePage.tsx
  src/stories/molecules/SearchTalkPickList.stories.tsx
  src/stories/organisms/SearchTalkPickListSection.stories.tsx
  src/stories/organisms/SearchTalkPickResult.stories.tsx
  src/types/search.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🪄refactor

#259 design: 마이페이지 모바일 ui 퍼블리싱
  src/assets/index.ts
  src/assets/svg/MobileBookmark.svg
  src/assets/svg/MobileBookmarkDF.svg
  src/assets/svg/MobileComment.svg
  src/assets/svg/MobileCommentDF.svg
  src/assets/svg/MobileVote.svg
  src/assets/svg/MobileVoteDF.svg
  src/assets/svg/MobileWritten.svg
  src/assets/svg/MobileWrittenDF.svg
  src/assets/svg/camera.svg
  src/components/atoms/ChoiceInputButton/ChoiceInputButton.tsx
  src/components/atoms/ImageBoxButton/ImageBoxButton.style.ts
  src/components/atoms/ImageBoxButton/ImageBoxButton.tsx
  src/components/atoms/ImageUploadButton/ImageUploadButton.style.ts
  src/components/atoms/ImageUploadButton/ImageUploadButton.tsx
  src/components/mobile/atoms/MobileProfileImage/MobileProfileImage.stories.tsx
  src/components/mobile/atoms/MobileProfileImage/MobileProfileImage.style.ts
  src/components/mobile/atoms/MobileProfileImage/MobileProfileImage.tsx
  src/components/mobile/atoms/PhotoBox/PhotoBox.stories.tsx
  src/components/mobile/atoms/PhotoBox/PhotoBox.style.ts
  src/components/mobile/atoms/PhotoBox/PhotoBox.tsx
  src/components/mobile/atoms/SelectGroup/SelectGroup.stories.tsx
  src/components/mobile/atoms/SelectGroup/SelectGroup.style.ts
  src/components/mobile/atoms/SelectGroup/SelectGroup.tsx
  src/components/mobile/molecules/IconButton/IconButton.stories.tsx
  src/components/mobile/molecules/IconButton/IconButton.style.ts
  src/components/mobile/molecules/IconButton/IconButton.tsx
  src/components/mobile/molecules/LabelCountBox/LabelCountBox.stories.tsx
  src/components/mobile/molecules/LabelCountBox/LabelCountBox.style.ts
  src/components/mobile/molecules/LabelCountBox/LabelCountBox.tsx
  src/components/mobile/molecules/OptionCard/OptionCard.stories.tsx
  src/components/mobile/molecules/OptionCard/OptionCard.style.ts
  src/components/mobile/molecules/OptionCard/OptionCard.tsx
  src/components/mobile/molecules/ProfileListItem/ProfileListItem.stories.tsx
  src/components/mobile/molecules/ProfileListItem/ProfileListItem.style.ts
  src/components/mobile/molecules/ProfileListItem/ProfileListItem.tsx
  src/components/mobile/organisms/DateGroupedList/DateGroupedList.stories.tsx
  src/components/mobile/organisms/DateGroupedList/DateGroupedList.style.ts
  src/components/mobile/organisms/DateGroupedList/DateGroupedList.tsx
  src/components/mobile/organisms/IconButtonArea/IconButtonArea.stories.tsx
  src/components/mobile/organisms/IconButtonArea/IconButtonArea.style.ts
  src/components/mobile/organisms/IconButtonArea/IconButtonArea.tsx
  src/components/mobile/organisms/ProfileInfoCard/ProfileInfoCard.stories.tsx
  src/components/mobile/organisms/ProfileInfoCard/ProfileInfoCard.style.ts
  src/components/mobile/organisms/ProfileInfoCard/ProfileInfoCard.tsx
  src/stories/atoms/ImageBoxButton.stories.tsx
Labels: 👩🏻‍💻 frontend, 🎨 markup
