Repository JECT-Study/PICK-O-Client, pull requests merged in 2025-01, with the labels that each got.

#272 feat: 웹 배너 리팩토링 및 모바일 배너 추가
  src/api/talk-pick.ts
  src/assets/images/game-banner-first.png
  src/assets/images/game-banner-second.png
  src/assets/images/mo-game-banner-first.png
  src/assets/images/mo-game-banner-second.png
  src/assets/images/mo-talk-pick-banner-first.png
  src/assets/images/mo-talk-pick-banner-second.png
  src/assets/images/talk-pick-banner-first.png
  src/assets/images/talk-pick-banner-second.png
  src/assets/index.ts
  src/components/molecules/TopBanner/Banner.style.ts
  src/components/molecules/TopBanner/TodayBalanceGameBanner/TodayBalanceGameBanner.style.ts
  src/components/molecules/TopBanner/TodayBalanceGameBanner/TodayBalanceGameBanner.tsx
  src/components/molecules/TopBanner/TodayTalkPickBanner/TodayTalkPickBanner.style.ts
  src/components/molecules/TopBanner/TodayTalkPickBanner/TodayTalkPickBanner.tsx
  src/components/molecules/TopBanner/TopBanner.tsx
  src/hooks/api/talk-pick/useTodayTalkPickQuery.ts
  src/hooks/game/useTodayBalanceGameList.ts
  src/mocks/data/banner.ts
  src/pages/LandingPage/LandingPage.tsx
  src/stories/molecules/TopBanner.stories.tsx
  src/styles/color.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#278 feat: 톡픽 요약 상태에 따른 UI 수정
  src/api/talk-pick.ts
  src/assets/index.ts
  src/assets/svg/sad-emoji.svg
  src/assets/svg/status-fail.svg
  src/assets/svg/status-not-required.svg
  src/components/molecules/SummaryBox/SummaryBox.style.ts
  src/components/molecules/SummaryBox/SummaryBox.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
  src/constants/message.ts
  src/hooks/api/talk-pick/useCreateTalkPickMutation.ts
  src/hooks/api/talk-pick/useEditTalkPickMutation.ts
  src/hooks/api/talk-pick/useTalkPickSummaryMutation.ts
  src/types/talk-pick.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#279 refactor: 로그인 관련 기능 개선
  src/App.tsx
  src/api/interceptor.ts
  src/api/member.ts
  src/components/molecules/CommentItem/CommentItem.tsx
  src/components/molecules/LoginForm/LoginForm.style.ts
  src/components/molecules/LoginForm/LoginForm.tsx
  src/components/molecules/ReplyItem/ReplyItem.tsx
  src/components/organisms/BalanceGameSection/BalanceGameSection.tsx
  src/components/organisms/CommentsSection/CommentsSection.tsx
  src/components/organisms/Header/Header.tsx
  src/constants/api.ts
  src/constants/message.ts
  src/hooks/api/member/useChangeUserInfoMutation.ts
  src/hooks/api/member/useLogoutMutation.ts
  src/hooks/api/member/useMemberQuery.ts
  src/hooks/common/useTokenRefresh.ts
  src/hooks/login/useLoginForm.ts
  src/pages/BalanceGamePage/BalanceGamePage.tsx
  src/pages/ChangeUserInfoPage/ChangeUserInfoPage.style.ts
  src/pages/ChangeUserInfoPage/ChangeUserInfoPage.tsx
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/TalkPickPage/TalkPickPage.tsx
  src/types/member.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🗝️로그인

#283 fix: 옵셔널 체이닝 미사용으로 인한 summaryStatus undefined 접근 에러 수정
  src/components/molecules/SummaryBox/SummaryBox.tsx
  src/components/organisms/TalkPickSection/TalkPickSection.tsx
Labels: 🐛bug

#280 feat: 밸런스게임 제작 모바일 페이지 ui 구현 및 api 연동
  src/App.tsx
  src/api/game.ts
  src/assets/index.ts
  src/assets/svg/mobile-choice-minus.svg
  src/assets/svg/mobile-choice-plus.svg
  src/assets/svg/mobile-trash-can.svg
  src/components/mobile/atoms/BalanceGameButton/BalanceGameButton.style.ts
  src/components/mobile/atoms/BalanceGameButton/BalanceGameButton.tsx
  src/components/mobile/atoms/Button/Button.style.ts
  src/components/mobile/atoms/Button/Button.tsx
  src/components/mobile/atoms/DraftSaveButton/DraftSaveButton.style.ts
  src/components/mobile/atoms/Modal/Modal.style.ts
  src/components/mobile/atoms/Modal/Modal.tsx
  src/components/mobile/atoms/PhotoBox/PhotoBox.style.ts
  src/components/mobile/atoms/PhotoBox/PhotoBox.tsx
  src/components/mobile/atoms/TitleDescriptionField/TitleDescriptionField.tsx
  src/components/mobile/molecules/GameTagModal/GameTagModal.style.ts
  src/components/mobile/molecules/GameTagModal/GameTagModal.tsx
  src/components/mobile/molecules/OptionCard/OptionCard.stories.tsx
  src/components/mobile/molecules/OptionCard/OptionCard.style.ts
  src/components/mobile/molecules/OptionCard/OptionCard.tsx
  src/components/mobile/molecules/TextModal/TextModal.style.ts
  src/components/mobile/molecules/TextModal/TextModal.tsx
  src/components/mobile/organisms/BalanceGameCreateSection/BalanceGameCreateSection.style.ts
  src/components/mobile/organisms/BalanceGameCreateSection/BalanceGameCreateSection.tsx
  src/components/mobile/organisms/BalanceGameSection/BalanceGameSection.tsx
  src/constants/game.ts
  src/hooks/api/game/useCreateGameMutation.ts
  src/hooks/game/useGameInputs.ts
  src/hooks/game/usePostBalanceGameForm.ts
  src/hooks/game/validateBalanceGameForm.ts
  src/pages/mobile/BalanceGameCreationMobilePage/BalanceGameCreationMobilePage.style.ts
  src/pages/mobile/BalanceGameCreationMobilePage/BalanceGameCreationMobilePage.tsx
  src/stories/mobile/atoms/Button.stories.tsx
  src/stories/mobile/atoms/Modal.stories.tsx
  src/stories/mobile/atoms/PhotoBox.stories.tsx
  src/stories/mobile/atoms/TitleDescriptionField.stories.tsx
  src/stories/mobile/molecules/GameTagModal.stories.tsx
  src/stories/mobile/molecules/OptionCard.stories.tsx
  src/stories/mobile/molecules/TextModal.stories.tsx
  src/stories/mobile/organisms/BalanceGameCreateSection.stories.tsx
  src/stories/mobile/organisms/BalanceGameSection.stories.tsx
  src/utils/balanceGameUtils.ts
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, 🎨 markup, ✅feature
