Repository JECT-Study/PICK-O-Client, pull requests merged in 2025-02, with the labels that each got.

#268 feat: 밸런스 게임 수정 및 삭제 로직 구현
  src/App.tsx
  src/api/game.ts
  src/components/molecules/TagModal/TagModal.tsx
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.style.ts
  src/components/organisms/BalanceGameCreation/BalanceGameCreation.tsx
  src/components/organisms/BalanceGameList/BalanceGameList.tsx
  src/components/organisms/BalanceGameSection/BalanceGameSection.tsx
  src/constants/game.ts
  src/constants/message.ts
  src/constants/path.ts
  src/hooks/api/game/useDeleteGameSetMutation.ts
  src/hooks/api/game/useEditGamesMutation.ts
  src/hooks/game/useBalanceGameCreation.ts
  src/hooks/game/useImageHandlers.ts
  src/hooks/modal/useModal.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.style.ts
  src/pages/BalanceGameCreationPage/BalanceGameCreationPage.tsx
  src/pages/BalanceGameEditPage/BalanceGameEditPage.tsx
  src/pages/BalanceGamePage/BalanceGamePage.style.ts
  src/pages/BalanceGamePage/BalanceGamePage.tsx
  src/stories/organisms/BalanceGameCreation.stories.tsx
  src/types/game.ts
  src/utils/balanceGameUtils.ts
Labels: 👩🏻‍💻 frontend, ✅feature

#290 refactor: SSE 알림 연결 오류 수정
  src/App.tsx
  src/api/notifications.ts
  src/assets/index.ts
  src/assets/svg/mobile-back-button.svg
  src/components/atoms/NotificationItem/NotificationItem.style.ts
  src/components/mobile/molecules/NotificationHeader/NotificationHeader.style.ts
  src/components/mobile/molecules/NotificationHeader/NotificationHeader.tsx
  src/components/molecules/Notification/Notification.tsx
  src/components/organisms/Header/Header.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/pages/mobile/NotificationPage/NotificationPage.style.ts
  src/pages/mobile/NotificationPage/NotificationPage.tsx
  src/types/notification.ts
Labels: ✨feature, 👩🏻‍💻 frontend

#286 refactor: 로그인 상태 확인 전 페이지 이동 문제 수정
  src/App.tsx
  src/components/Routes/ProtectedRoutes.tsx
  src/hooks/common/useTokenRefresh.ts
  src/pages/LoadingPage/LoadingPage.style.ts
  src/pages/LoadingPage/LoadingPage.tsx
  src/store/auth.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻 frontend, 🗝️로그인

#294 feat: 모바일 주제별 밸런스 게임 목록 페이지 UI 구현 및 api 연결
  src/App.tsx
  src/api/notifications.ts
  src/assets/index.ts
  src/assets/svg/couple-medium.svg
  src/assets/svg/more-small.svg
  src/assets/svg/popular-medium.svg
  src/assets/svg/taste-medium.svg
  src/components/atoms/MoreButton/MoreButton.style.ts
  src/components/atoms/MoreButton/MoreButton.tsx
  src/components/mobile/atoms/BalanceGameCategory/BalanceGameCategory.style.ts
  src/components/mobile/atoms/BalanceGameCategory/BalanceGameCategory.tsx
  src/components/mobile/organisms/BalanceGameCategorySection/BalanceGameCategorySection.style.ts
  src/components/mobile/organisms/BalanceGameCategorySection/BalanceGameCategorySection.tsx
  src/components/molecules/SearchGameList/SearchGameList.tsx
  src/components/organisms/Header/Header.style.ts
  src/components/organisms/MyBalanceGameList/MyBalanceGameList.tsx
  src/constants/path.ts
  src/hooks/api/game/useCreateGameMutation.ts
  src/pages/mobile/BalanceGameCategoriesPage/BalanceGameCategoriesPage.style.ts
  src/pages/mobile/BalanceGameCategoriesPage/BalanceGameCategoriesPage.tsx
  src/stories/mobile/atoms/BalanceGameCategory.stories.tsx
  src/stories/mobile/organisms/BalanceGameCategorySection.stories.tsx
Labels: ✔︎pull requests, 👩🏻‍💻 frontend, ✅feature

#298 refactor: 메인 페이지 카테고리 버튼 2개로 수정
  src/components/atoms/CategoryButton/CategoryButton.style.ts
  src/components/molecules/CategoryBox/CategoryBox.style.ts
  src/components/molecules/CategoryBox/CategoryBox.tsx
  src/styles/typo.ts
Labels: ✨feature, 👩🏻‍💻 frontend

#299 fix: 페이지네이션 적용된 페이지에서 뒤로가기 로직 오류 수정
  src/hooks/search/usePagination.ts
Labels: 🐛bug

#304 fix: 랜딩페이지 렌더링 이슈 해결
  src/pages/LandingPage/LandingPage.tsx
Labels: 🐛bug
